[pytest]
addopts = --pyargs --doctest-modules --doctest-ignore-import-errors
markers =
    now
python_files = tests.py test_*.py
doctest_optionflags = NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE ELLIPSIS
